[workspace]
members = [
    "vectura-common",
    "vectura-ebpf",
    "vectura-agent",
    "xtask"
]

# Only build the user-space agent and xtask during a standard `cargo build`
default-members = ["vectura-agent", "xtask"]
resolver = "2"

# Profiles moved here to apply across the whole workspace
[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
debug = true
panic = "abort"