[package]
name = "vectura-ebpf"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "vectura_ebpf"
path = "src/main.rs"

[dependencies]
aya-ebpf = "0.1"
vectura-common = { path = "../vectura-common" }

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
debug = true
panic = "abort"